# Generated by Django 3.1.1 on 2020-09-28 18:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PollApp', '0002_auto_20200928_1131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='poll',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='PollApp.poll'),
        ),
    ]
