# Generated by Django 3.1.1 on 2020-09-28 19:27

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('PollApp', '0003_auto_20200928_1143'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='url',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
        migrations.DeleteModel(
            name='Link',
        ),
    ]
