# Generated by Django 3.1.1 on 2020-09-29 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PollApp', '0004_auto_20200928_1227'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='tally',
            field=models.IntegerField(default=0),
        ),
    ]
