# Generated by Django 3.1.1 on 2020-10-05 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PollApp', '0005_answer_tally'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='chart',
            field=models.ImageField(blank=True, default='default.png', upload_to=''),
        ),
    ]
