# Generated by Django 3.1.1 on 2020-10-09 23:20

from django.db import migrations
import shortuuidfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('PollApp', '0006_poll_chart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='url',
            field=shortuuidfield.fields.ShortUUIDField(blank=True, editable=False, max_length=22),
        ),
    ]
