# Generated by Django 3.1.1 on 2020-10-09 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PollApp', '0008_auto_20201009_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='answers_amount',
            field=models.IntegerField(),
        ),
    ]
