# Generated by Django 3.1.2 on 2020-10-13 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PollApp', '0009_auto_20201009_1627'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poll',
            name='chart',
        ),
    ]
